### ISSUE TITLE
Option to disable minification

### ISSUE THREAD

**Issue by connorjclark** [esbuild-kit/esm-loader#18]
I'm using this loader in order to run `.tsx` files in Mocha, but I noticed when attaching a debugger that the scripts were minified. It'd be nice to be able to configure the esbuild minification option to improve debugging.

**Comment by privatenumber** [comment]
Should be fixed in the latest core-utils release.

You can update the subdependency or reinstall tsx

**Comment by privatenumber** [comment]
Closing as fixed & duplicate of https://github.com/esbuild-kit/core-utils/issues/7
