### ISSUE TITLE
Problems running on GitHub actions across pnpm workspaces

### ISSUE THREAD

**Issue by codepunkt** [esbuild-kit/esm-loader#36]
I have no clue what's happening 😐
I use this package as a `--loader` argument to node when running my @avajs tests.

Everything is working fine when executed locally, GitHub actions throws this at me, where this package seems to have problems resolving local pnpm workspace dependencies?

![image](https://user-images.githubusercontent.com/603683/185232864-1f4947ad-6f43-42e1-8a61-9137143d86e6.png)
(https://github.com/wilsonjs/wilson2/runs/7886347702?check_suite_focus=true)

Might be similar to #9, which seems fixed though.

@esbuild-kit/esm-loader is configured for @avajs tests here:
https://github.com/wilsonjs/wilson2/blob/f4bcf26c8279c01198096204ba766b7b416fa11f/packages/utils/ava.config.js#L9

**Comment by privatenumber** [comment]
Thanks for the issue.

Can you provide a minimal reproduction of the problem? Based on this, I can't tell if this is a tsx bug or a problem in your project configuration.

**Comment by codepunkt** [comment]
@privatenumber It was a rather stupid oversight on my end. In the middle of producing a reproduction I realized my mistake and fixed it in the original repo.

Turns out you need to build dependencies before you can use them in a test 😔
