### ISSUE TITLE
Can't resolve directory import

### ISSUE THREAD

**Issue by SettingDust** [esbuild-kit/esm-loader#45]
`import('./content-extractor')` is failed. It's fine after add `/index`.
![image](https://user-images.githubusercontent.com/19922286/203027727-b4c4edaf-74ec-4ad4-95ff-432a4fcee52f.png)
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/E:/javascript/article-extractor/src/content-extractor' imported from E:\javascript\article-extractor\src\default-extractors.ts
```

**Comment by privatenumber** [comment]
Please provide a reproduction.

Works for me:
https://stackblitz.com/edit/node-d2fp3u?file=index.ts

**Comment by SettingDust** [comment]
I can't reproduce it in the playground. The stackblitz is stuck at `Running start command` for half hours.
There is a project I facing that. 
If there isn't `/index` at https://github.com/SettingDust/article-extractor/blob/main/src/default-extractors.ts#L13 and running the `test` npm script. The problem will appear.

**Comment by privatenumber** [comment]
Happy to help but you'll have to provide a reproduction. Not just a link to your codebase.

I recommend cloning your codebase and deleting everything until the bug is no longer reproducible. Also remove mocha, to make sure that the bug is not in there instead of esm-loader.

**Comment by SettingDust** [comment]
Mocha iss fine with ts-node and swc. So I think not relate to mocha.
I'll try to find out a reproduction of course

**Comment by SettingDust** [comment]
I found the reason. Caused by `--experimental-specifier-resolution=node`
