### ISSUE TITLE
options to disable minify?

### ISSUE THREAD

**Issue by trim21** [esbuild-kit/esm-loader#58]
I'm migrating from `ts-node/esm` to this loader, and I have a rare use case to expecting output not being minified.

Is this a feature you considering to add?

**Comment by trim21** [comment]
> Not currently. Why?

I have a project that need some type checking which ts doesn't support (or very hard to write types, like a generic type infer from object attr and apply it on another attr), so the tests are written on code directly, which need transformed to not being minified.

**Comment by privatenumber** [comment]
I'll need to see some real code examples if you want me to consider it.

Closing for now, but happy to re-open when a valid use-case is provided.

**Comment by privatenumber** [comment]
Yes, I'm against it because you haven't shown me any code/examples that explains why.

**Comment by trim21** [comment]
> Yes, I'm against it because you haven't shown me any code/examples that explains why.

I'm using esm loader with mocha in testing.

In testing, I will import ts files, contains many objects, and I need to test these objects meet my expection.

like this:

```ts
    {
      id: 'Euphrosyne Halone Ice Dart',
      type: 'StartsUsing',
      netRegex: { id: '7D66', source: 'Halone' },
      alertText: (data, matches, output) => {
        if (data.me === matches.target)
          return output.spread!();
      },
      run: (data, matches) => data.haloneIceDartTargets.push(matches.target),
      outputStrings: {
        spread: Outputs.spread,
      },
    },
```

here, `matches` and `output` has only expected properties, and I can only know these properties in **runtime**, so I can't use a lint or ts types to check it, and I can't invoke `run` in testing, So I will have to use `run.toString()` to get raw function def and test it with some regex pattern like `/matches\,(.*)/` or `/output\,(.*)/` (not actually regex pattern, just example) and check if these properties are valid.

`ts-node/esm` keep whitespace and line break (and even comment) so I can expected it's just js code without ts types.

(🤔 In face I'd expect a `esbuild-kit/loader` (or other key) in tsconfig.json to pass some more options to esbuild api, not only disable minify)


But esbuild-kit loaders do minification and and it will break old testing.

**Comment by privatenumber** [comment]
> So I will have to use run.toString() to get raw function def and test it with some regex pattern like /matches\,(.*)/ or /output\,(.*)/ (not actually regex pattern, just example) and check if these properties are valid.

Why check against a parameter name? Can't someone call it `randomVariable`, still be valid at runtime, but break your check because it's not called `matches`?

Maybe you can use [acorn](https://github.com/acornjs/acorn) or another JS parser if you want to check with precision.

**Comment by trim21** [comment]
> Why check against a parameter name? Can't someone call it `randomVariable`, still be valid at runtime, but break your check because it's not called `matches`?

This is not a problem, we have a lint for that, is will be `matches` for sure.


> Maybe you can use [acorn](https://github.com/acornjs/acorn) or another JS parser if you want to check with precision.

Yes I know I can parse AST, but make loader to do transformation instead of minification would be much easier solution for us. 🤔
