### ISSUE TITLE
CSS modules support

### ISSUE THREAD

**Issue by adamraine** [esbuild-kit/esm-loader#65]
The [esbuild CSS loader](https://esbuild.github.io/content-types/#css) works fine for production builds. However this package doesn't appear to support the CSS loader. I get a `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css"` when attempting to run the code directly using `esm-loader`.

Is it possible to support the CSS loader from esbuild?

**Comment by privatenumber** [comment]
Nope. This is project aims for TypeScript parity, not esbuild parity.
