### ISSUE TITLE
Using multiple loaders

### ISSUE THREAD

**Issue by fatso83** [esbuild-kit/esm-loader#66]
You hint to using this alongside CJS in the README, but I cannot see any hints on how to do so. AFAIK, NodeJS does currently not support multiple loaders (but [work is on the way](https://github.com/nodejs/loaders#purpose)), so I was wondering how you intended folks to do this? Write some kind of wrapper that delegated to the right loaders?

**Comment by privatenumber** [comment]
Isn't it demonstrated in the first example here?
https://nodejs.org/api/esm.html#loaders

**Comment by fatso83** [comment]
Jeebus. I just saw a bunch of different configs where the config only accepted a single string argument for `loader` and assumed this meant Node did not support more than a single loader argument, which was backed by the current work I linked, but did not think about checking the docs for some reason.
